package Vista;

import Modelado.CConexion;
import java.sql.Connection;
import javax.swing.JButton;

/**
 *
 * @author Usuario
 */
public class AdminMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMenu.class.getName());
    
   private Connection conexion;

    public AdminMenu(Connection conexion) {
    this.conexion = conexion;
    initComponents();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnProductores = new javax.swing.JButton();
        btnTecnicos = new javax.swing.JButton();
        btnPropietarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnAsignarInspeccion = new javax.swing.JButton();
        btnReporteGlobal = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));
        jPanel1.setForeground(new java.awt.Color(0, 99, 17));

        Titulo.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Panel del Administrador");

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ICA logo 109.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 130));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 255, 204));

        btnProductores.setBackground(new java.awt.Color(125, 163, 130));
        btnProductores.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnProductores.setForeground(new java.awt.Color(255, 255, 255));
        btnProductores.setText("🌱Gestionar Productores");

        btnTecnicos.setBackground(new java.awt.Color(125, 163, 130));
        btnTecnicos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        btnTecnicos.setText("🛠️Gestionar tecnicos");

        btnPropietarios.setBackground(new java.awt.Color(125, 163, 130));
        btnPropietarios.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnPropietarios.setForeground(new java.awt.Color(255, 255, 255));
        btnPropietarios.setText("👷 Gestionar Propietarios");
        btnPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietariosActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(125, 163, 130));
        btnReportes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("📊 Generar Reporte Solicitud");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnAsignarInspeccion.setBackground(new java.awt.Color(125, 163, 130));
        btnAsignarInspeccion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnAsignarInspeccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignarInspeccion.setText("Asignar Inspeccion");

        btnReporteGlobal.setBackground(new java.awt.Color(125, 163, 130));
        btnReporteGlobal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnReporteGlobal.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteGlobal.setText("📊 Generar Reporte Global");
        btnReporteGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteGlobalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPropietarios, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnAsignarInspeccion, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnReporteGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProductores, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnProductores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAsignarInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporteGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 370));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 99, 17));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 99, 17), 1, true));
        fondo.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 270, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 99, 17));
        jLabel1.setText("👋¡Bienvenido al panel del Administrador!");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Aqui puede administrar la informacion de productores, tecnicos y propietarios, y consultar");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 490, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("los reportes del sistema.");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnProductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoresActionPerformed

    private void btnTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecnicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTecnicosActionPerformed

    private void btnPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPropietariosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnReporteGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteGlobalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteGlobalActionPerformed
    
   
    public JButton getBtnProductores() { return btnProductores; }
    public JButton getBtnTecnicos() { return btnTecnicos; }
    public JButton getBtnPropietarios() { return btnPropietarios; }
    public JButton getBtnReportes() { return btnReportes; }
    public JButton getBtnCerrarSesion() { return btnCerrarSesion; }
    public JButton getBtnAsignarInspeccion(){return btnAsignarInspeccion;}
    public JButton getBtnReporteGlobal(){return btnReporteGlobal;}
    
    
    
    
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
    Connection conexionActiva = CConexion.getConnection(); // usa tu clase real aquí

    AdminMenu vista = new AdminMenu(conexionActiva);
    new Controlador.ControladorMenuAdministrador(vista, conexionActiva);

    vista.setVisible(true);
});

}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnAsignarInspeccion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnProductores;
    private javax.swing.JButton btnPropietarios;
    private javax.swing.JButton btnReporteGlobal;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTecnicos;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
