package Vista;

import Controlador.ControladorMenuAdministrador;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class AsignarTecnico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AsignarTecnico.class.getName());

    /**
     * Creates new form AsignarTecnico
     */
    public AsignarTecnico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTecnicos = new javax.swing.JTable();
        btnAsignar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLotesPendientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 30, 490));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono100.png"))); // NOI18N
        jLabel3.setToolTipText("");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setForeground(new java.awt.Color(34, 103, 54));
        btnVolver.setText("⮜ Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 163, 130)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        fondo.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 100, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Asignar Tecnicos");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 260, -1));

        jPanel4.setBackground(new java.awt.Color(55, 165, 87));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        fondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 50, -1));

        tablaTecnicos.setBackground(new java.awt.Color(235, 255, 235));
        tablaTecnicos.setForeground(new java.awt.Color(0, 99, 17));
        tablaTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Tecnico", "Nombre", "Tipo Tecnico"
            }
        ));
        tablaTecnicos.setGridColor(new java.awt.Color(0, 99, 17));
        tablaTecnicos.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tablaTecnicos);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 380, 250));

        btnAsignar.setBackground(new java.awt.Color(204, 204, 204));
        btnAsignar.setForeground(new java.awt.Color(34, 103, 54));
        btnAsignar.setText("✔️ Asignar Tecnico");
        btnAsignar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 163, 130)));
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        fondo.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 140, 30));

        jPanel2.setBackground(new java.awt.Color(55, 165, 87));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 700, 5));

        tablaLotesPendientes.setBackground(new java.awt.Color(235, 255, 235));
        tablaLotesPendientes.setForeground(new java.awt.Color(0, 99, 17));
        tablaLotesPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N° Lote", "Nombre Lote", "Area", "Estado"
            }
        ));
        tablaLotesPendientes.setGridColor(new java.awt.Color(0, 99, 17));
        tablaLotesPendientes.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane2.setViewportView(tablaLotesPendientes);

        fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 380, 250));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(125, 163, 130));
        jLabel2.setText("Lotes Pendientes (Sin aprobar)");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(125, 163, 130));
        jLabel4.setText("Tecnicos Disponibles");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 410, 290));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        fondo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
 
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarActionPerformed

    public JTable getTablaLotesPendientes() { return tablaLotesPendientes; }
    public JTable getTablaTecnicos() { return tablaTecnicos; }
    public JButton getBtnAsignar() { return btnAsignar; }
    public JButton getBtnVolver() { return btnVolver; }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AsignarTecnico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaLotesPendientes;
    private javax.swing.JTable tablaTecnicos;
    // End of variables declaration//GEN-END:variables
}
