package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class EditarPredio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarPredio.class.getName());

    /**
     * Creates new form EditarPredio
     */
    public EditarPredio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEditarNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEditarVereda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbEditarLugarProdu = new javax.swing.JComboBox<>();
        cmbEditarProductor = new javax.swing.JComboBox<>();
        cmbEditarDepartamento = new javax.swing.JComboBox<>();
        cmbEditarMunicipio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));
        jPanel1.setForeground(new java.awt.Color(0, 99, 17));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ica_logo_2-removebg-preview (2) (1).png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo.setText("Editar Predio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        btnGuardarCambios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGuardarCambios.setForeground(new java.awt.Color(0, 99, 17));
        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 165, 87), 1, true));
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        fondo.add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 270, 30));

        BtnRegresar.setBackground(new java.awt.Color(55, 165, 87));
        BtnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresar.setText("⮜ REGRESAR");
        BtnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        fondo.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setText("- Nombre (*):");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        txtEditarNombre.setBackground(new java.awt.Color(225, 237, 227));
        txtEditarNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        txtEditarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarNombreActionPerformed(evt);
            }
        });
        fondo.add(txtEditarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("- Departamento (*): ");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("- Municipio (*): ");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 360, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("- Lugar de produccion (*): ");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 360, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setText("- Productor (*): ");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 360, -1));

        txtEditarVereda.setBackground(new java.awt.Color(225, 237, 227));
        txtEditarVereda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        txtEditarVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarVeredaActionPerformed(evt);
            }
        });
        fondo.add(txtEditarVereda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 310, 20));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel9.setText("- Vereda (*):");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 360, -1));

        cmbEditarLugarProdu.setBackground(new java.awt.Color(225, 237, 227));
        cmbEditarLugarProdu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbEditarLugarProdu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbEditarLugarProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 310, -1));

        cmbEditarProductor.setBackground(new java.awt.Color(225, 237, 227));
        cmbEditarProductor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbEditarProductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbEditarProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 310, -1));

        cmbEditarDepartamento.setBackground(new java.awt.Color(225, 237, 227));
        cmbEditarDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbEditarDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 310, -1));

        cmbEditarMunicipio.setBackground(new java.awt.Color(225, 237, 227));
        cmbEditarMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbEditarMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void txtEditarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarNombreActionPerformed

    private void txtEditarVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarVeredaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditarVeredaActionPerformed

    public JButton getBtnRegresar() { return BtnRegresar; }
    public JButton getBtnGuardarCambios() { return btnGuardarCambios; }
    public JTextField gettxtEditarnombre() { return txtEditarNombre; }
    public JTextField gettxtEditarVereda() { return txtEditarVereda; }
    public JComboBox getcmbEditarDepartamento() { return cmbEditarDepartamento; }
    public JComboBox getcmbEditarMunicipio() { return cmbEditarMunicipio; }
    public JComboBox getcmbEditarProdutor() { return cmbEditarProductor; }
    public JComboBox getcmbEditarLugarProdu() { return cmbEditarLugarProdu; }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarPredio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JComboBox<String> cmbEditarDepartamento;
    private javax.swing.JComboBox<String> cmbEditarLugarProdu;
    private javax.swing.JComboBox<String> cmbEditarMunicipio;
    private javax.swing.JComboBox<String> cmbEditarProductor;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEditarNombre;
    private javax.swing.JTextField txtEditarVereda;
    // End of variables declaration//GEN-END:variables
}
