package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JTable;
import javax.swing.JButton;

/**
 *
 * @author Usuario
 */
public class GestionPropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionPropietario.class.getName());

    /**
     * Creates new form GestionPropietario
     */
    public GestionPropietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPropi = new javax.swing.JTable();
        TxtBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnActualizar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono100.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnVolver.setBackground(new java.awt.Color(55, 165, 87));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("⮜ REGRESAR");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fondo.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 103, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Propietarios");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, 80));

        jPanel1.setBackground(new java.awt.Color(75, 133, 82));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 20, 420));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 165, 87)));

        TablaPropi.setBackground(new java.awt.Color(224, 224, 224));
        TablaPropi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 165, 87)));
        TablaPropi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TablaPropi.setForeground(new java.awt.Color(55, 165, 87));
        TablaPropi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Documento", "Nombre", "Telefono", "Correo", "Contraseña"
            }
        ));
        TablaPropi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaPropi.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TablaPropi);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 720, 230));

        TxtBuscar.setForeground(new java.awt.Color(76, 107, 80));
        TxtBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 163, 130), 1, true));
        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        fondo.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 190, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 103, 54));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono100.png"))); // NOI18N
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, -1, -1));

        BtnActualizar.setBackground(new java.awt.Color(212, 240, 221));
        BtnActualizar.setForeground(new java.awt.Color(34, 103, 54));
        BtnActualizar.setText("🔃 Actualizar");
        BtnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 163, 130), 1, true));
        fondo.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, 30));

        BtnAgregar.setBackground(new java.awt.Color(212, 240, 221));
        BtnAgregar.setForeground(new java.awt.Color(34, 103, 54));
        BtnAgregar.setText("➕ Agregar");
        BtnAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 163, 130), 1, true));
        fondo.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 100, 30));

        BtnEditar.setBackground(new java.awt.Color(212, 240, 221));
        BtnEditar.setForeground(new java.awt.Color(34, 103, 54));
        BtnEditar.setText("📝 Editar");
        BtnEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 163, 130), 1, true));
        fondo.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 100, 30));

        BtnEliminar.setBackground(new java.awt.Color(212, 240, 221));
        BtnEliminar.setForeground(new java.awt.Color(34, 103, 54));
        BtnEliminar.setText("➖ Eliminar");
        BtnEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(125, 163, 130), 1, true));
        fondo.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    public JButton getBtnActualizar() { return BtnActualizar; }
    public JButton getBtnAgregar() { return BtnAgregar; }
    public JButton getBtnEditar() { return BtnEditar; }
    public JButton getBtnEliminar() { return BtnEliminar; }
    public JButton getBtnVolver() { return BtnVolver; }
    public JTable getTablaPropietarios() { return TablaPropi;}
    
    public static void main(String args[]) {
       /* Configurar el estilo visual Nimbus */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Crear y mostrar la vista con su controlador */
    java.awt.EventQueue.invokeLater(() -> {
        GestionPropietario vista = new GestionPropietario();
        new Controlador.ControladorGestionProp(vista); // 🔹 Conexión vista-controlador
        vista.setLocationRelativeTo(null); // Centra la ventana
        vista.setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTable TablaPropi;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
