package Vista;

import Controlador.ControladorLogin;
import Vista.vistas;
import java.sql.Connection;
import javax.swing.JButton;
import Controlador.ControladorAdministrarLotes;
import Controlador.ControladorAdministrarPredio;

/**
 *
 * @author Usuario
 */
public class MenuPropietario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPropietario.class.getName());

    /**
     * Creates new form MenuPropietario
     */
    private Connection conexion;
    private int docPropietario;

    // ========================================
    // CONSTRUCTOR
    // ========================================
    public MenuPropietario(Connection conexion, int docPropietario) {
        this.conexion = conexion;
        this.docPropietario = docPropietario;

        initComponents();
        inicializarEventos();
    }

    // ========================================
    // EVENTOS DE BOTONES
    // ========================================
    private void inicializarEventos() {
        btnAdministrarLote.addActionListener(e -> abrirAdministrarLotes());
        btnAdministrarPredio.addActionListener(e -> abrirAdministrarPredio());
        btnCerrarSesion.addActionListener(e -> cerrarSesion());
    }

    // ========================================
    // ABRIR ADMINISTRAR LOTES
    // ========================================
    private void abrirAdministrarLotes() {
        AdministrarLotes vista = new AdministrarLotes(conexion, docPropietario);
        ControladorAdministrarLotes controlador = new ControladorAdministrarLotes(vista, conexion);

        vista.setVisible(true);
        this.dispose();
    }

    // ========================================
    // ABRIR ADMINISTRAR PREDIOS
    // ========================================
    private void abrirAdministrarPredio() {
        AdministrarPredios vista = new AdministrarPredios(conexion,docPropietario);
        ControladorAdministrarPredio controlador = new ControladorAdministrarPredio(vista, conexion, docPropietario);

        vista.setVisible(true);
        this.dispose();
    }

    // ========================================
    // CERRAR SESIÓN
    // ========================================
    private void cerrarSesion() {
        Vista.vistas login = new Vista.vistas();
        new ControladorLogin(login);
        login.setVisible(true);
        this.dispose();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAdministrarLote = new javax.swing.JButton();
        btnGenerarInforme = new javax.swing.JButton();
        btnAdministrarPredio = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 99, 17));
        jPanel2.setForeground(new java.awt.Color(0, 99, 17));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú de Propietario");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ICAlogo90.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        btnAdministrarLote.setBackground(new java.awt.Color(125, 163, 130));
        btnAdministrarLote.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAdministrarLote.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarLote.setText("🌲 Administrar Lotes");

        btnGenerarInforme.setBackground(new java.awt.Color(125, 163, 130));
        btnGenerarInforme.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnGenerarInforme.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarInforme.setText("📋 Generar Informe");

        btnAdministrarPredio.setBackground(new java.awt.Color(125, 163, 130));
        btnAdministrarPredio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAdministrarPredio.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarPredio.setText("🌳 Administrar Predios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdministrarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAdministrarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAdministrarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 220, 370));

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 99, 17));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 99, 17), 1, true));
        fondo.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 270, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 99, 17));
        jLabel3.setText("👋¡Bienvenido al menú de Propietario!");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("En este menú podra administrar sus predios, lotes y generar un informe ");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 490, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("de sus lotes y predios");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ica Completo 100.png"))); // NOI18N
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnAdministrarLote() { return btnAdministrarLote; }
    public JButton getBtnAdministrarPredio() { return btnAdministrarPredio; }
    public JButton getBtnGenerarInforme() { return btnGenerarInforme; }
    public JButton getBtnCerrarSesion() { return btnCerrarSesion; }
    
    public static void main(String args[]) {
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarLote;
    private javax.swing.JButton btnAdministrarPredio;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGenerarInforme;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
