package Vista;

/**
 *
 * @author Usuario
 */

import Controlador.ControladorRegistro;
import javax.swing.JOptionPane; 
import Modelado.RegistrotecDAO;

public class Registrotec extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrotec.class.getName());

    public Registrotec() {
        initComponents();
        grupoTipo = new javax.swing.ButtonGroup();
        grupoTipo.add(rbtIca);
        grupoTipo.add(rbtParticular);

        // Por defecto, seleccionamos “Técnico del ICA”
        rbtIca.setSelected(true);

        // Comportamiento: activar/desactivar campo de tarjeta profesional
        rbtIca.addActionListener(e -> Text_numtarjtec.setEnabled(true));
        rbtParticular.addActionListener(e -> Text_numtarjtec.setEnabled(false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Button_siguiente = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Text_numtarjtec = new javax.swing.JTextField();
        rbtIca = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbtParticular = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Text_numdoctec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Text_nombretec = new javax.swing.JTextField();
        Text_telefonotec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Text_correotec = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_contrasena = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Text_telefonoaltertec = new javax.swing.JTextField();
        Text_correoaltertec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));
        jPanel1.setForeground(new java.awt.Color(0, 99, 17));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ICAlogo90.png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo.setText("Registro de Asistente Tecnico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        Button_siguiente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Button_siguiente.setForeground(new java.awt.Color(0, 99, 17));
        Button_siguiente.setText("Siguiente");
        Button_siguiente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 165, 87), 1, true));
        Button_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_siguienteActionPerformed(evt);
            }
        });
        fondo.add(Button_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 130, 30));

        BtnVolver.setBackground(new java.awt.Color(55, 165, 87));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("⮜ REGRESAR");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        fondo.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setText("- Numero de documento (*):");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 210, -1));

        Text_numtarjtec.setBackground(new java.awt.Color(225, 237, 227));
        Text_numtarjtec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_numtarjtec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_numtarjtecActionPerformed(evt);
            }
        });
        fondo.add(Text_numtarjtec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 20));

        rbtIca.setText("Asistente tecnico del ICA");
        rbtIca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtIcaActionPerformed(evt);
            }
        });
        fondo.add(rbtIca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setText("- Seleccione el tipo de asistente tecnico a registrar: ");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        rbtParticular.setText("Asistente tecnico particular");
        rbtParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtParticularActionPerformed(evt);
            }
        });
        fondo.add(rbtParticular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setText("-  Numero de tarjeta profesional (Solo aplica si es del ICA):");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, -1));

        Text_numdoctec.setBackground(new java.awt.Color(225, 237, 227));
        Text_numdoctec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_numdoctec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_numdoctecActionPerformed(evt);
            }
        });
        fondo.add(Text_numdoctec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 310, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("- Nombre completo (*): ");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 360, -1));

        Text_nombretec.setBackground(new java.awt.Color(225, 237, 227));
        Text_nombretec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_nombretec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_nombretecActionPerformed(evt);
            }
        });
        fondo.add(Text_nombretec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 310, 20));

        Text_telefonotec.setBackground(new java.awt.Color(225, 237, 227));
        Text_telefonotec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_telefonotec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_telefonotecActionPerformed(evt);
            }
        });
        fondo.add(Text_telefonotec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 310, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("- Numero de telefono (*): ");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 360, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("- Correo electronico (*):");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 360, -1));

        Text_correotec.setBackground(new java.awt.Color(225, 237, 227));
        Text_correotec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_correotec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_correotecActionPerformed(evt);
            }
        });
        fondo.add(Text_correotec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 310, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("- Contraseña (*): ");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 360, -1));

        TXT_contrasena.setBackground(new java.awt.Color(225, 237, 227));
        TXT_contrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        TXT_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_contrasenaActionPerformed(evt);
            }
        });
        fondo.add(TXT_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 310, 20));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setText("- Numero de telefono alternativo: ");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 360, -1));

        Text_telefonoaltertec.setBackground(new java.awt.Color(225, 237, 227));
        Text_telefonoaltertec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_telefonoaltertec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_telefonoaltertecActionPerformed(evt);
            }
        });
        fondo.add(Text_telefonoaltertec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 310, 20));

        Text_correoaltertec.setBackground(new java.awt.Color(225, 237, 227));
        Text_correoaltertec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_correoaltertec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_correoaltertecActionPerformed(evt);
            }
        });
        fondo.add(Text_correoaltertec, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 310, 20));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel9.setText("- Correo electronico alternativo: ");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 360, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_siguienteActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void Text_numtarjtecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_numtarjtecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_numtarjtecActionPerformed

    private void rbtIcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtIcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtIcaActionPerformed

    private void rbtParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtParticularActionPerformed

    private void Text_numdoctecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_numdoctecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_numdoctecActionPerformed

    private void Text_nombretecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_nombretecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_nombretecActionPerformed

    private void Text_telefonotecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_telefonotecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_telefonotecActionPerformed

    private void Text_correotecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_correotecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_correotecActionPerformed

    private void TXT_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_contrasenaActionPerformed

    private void Text_telefonoaltertecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_telefonoaltertecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_telefonoaltertecActionPerformed

    private void Text_correoaltertecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_correoaltertecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_correoaltertecActionPerformed

    public javax.swing.JButton getButton_siguiente() { return Button_siguiente; }
    public javax.swing.JButton getBtnVolver() { return BtnVolver; }
    public javax.swing.JTextField getText_numdoctec() { return Text_numdoctec; }
    public javax.swing.JTextField getText_numtarjtec() { return Text_numtarjtec; }
    public javax.swing.JTextField getText_nombretec() { return Text_nombretec; }
    public javax.swing.JTextField getText_telefonotec() { return Text_telefonotec; }
    public javax.swing.JTextField getText_correotec() { return Text_correotec; }
    public javax.swing.JTextField getTXT_contrasena() { return TXT_contrasena; }
    public javax.swing.JRadioButton getRadioICA() { return rbtIca; }
    public javax.swing.JRadioButton getRadioParticular() { return rbtParticular; }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrotec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrotec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrotec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrotec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrotec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton Button_siguiente;
    private javax.swing.JLabel Icon;
    private javax.swing.JTextField TXT_contrasena;
    private javax.swing.JTextField Text_correoaltertec;
    private javax.swing.JTextField Text_correotec;
    private javax.swing.JTextField Text_nombretec;
    private javax.swing.JTextField Text_numdoctec;
    private javax.swing.JTextField Text_numtarjtec;
    private javax.swing.JTextField Text_telefonoaltertec;
    private javax.swing.JTextField Text_telefonotec;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel fondo;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtIca;
    private javax.swing.JRadioButton rbtParticular;
    // End of variables declaration//GEN-END:variables
}
