package Vista;

import Controlador.ControladorMostrarLugares;
import Vista.AdministrarLotes;
import java.sql.Connection;
import Modelado.CConexion;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */

import Controlador.ControladorRegistroLote;

public class RegistroLote extends javax.swing.JFrame {
     private int idPropietario;
    private Connection conexionActiva;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroLote.class.getName());

    /**
     * Creates new form RegistroLote
     */
    
    public RegistroLote() {
    initComponents();
}

    public RegistroLote(Connection conexionActiva) {
    initComponents();
    this.conexionActiva = conexionActiva;
    this.idPropietario = idPropietario;
}

  



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        TxtNombre = new javax.swing.JTextField();
        TxtArea = new javax.swing.JTextField();
        comboCultivo = new javax.swing.JComboBox<>();
        comboLugar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 99, 17));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 390));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 99, 17));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Lote");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 99, 17));
        jLabel2.setText("- Lugar de Producción (*):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 99, 17));
        jLabel3.setText("- Nombre del lote(*):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 99, 17));
        jLabel4.setText("- Área (en Hectareas)(*):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 99, 17));
        jLabel5.setText("- Cultivo (*):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(102, 102, 102));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("⮜ Regresar");
        btnRegresar.setToolTipText("");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        btnRegresar.setMaximumSize(new java.awt.Dimension(76, 23));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 80, 30));

        btnRegistrar.setBackground(new java.awt.Color(55, 165, 87));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, 30));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));
        jPanel1.add(TxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, -1));

        comboCultivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, -1));

        comboLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLugarActionPerformed(evt);
            }
        });
        jPanel1.add(comboLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono80x63.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    Vista.AdministrarLotes menu = new Vista.AdministrarLotes(conexionActiva,idPropietario);

    // Crear controlador UNA sola vez
    Controlador.ControladorAdministrarLotes controlador =
            new Controlador.ControladorAdministrarLotes(menu, conexionActiva);

    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void comboLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLugarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public JButton getbtnRegistrar() { return btnRegistrar;}
    public JButton getbtnRegresar() { return btnRegresar;}
    public JTextField getTxtNombre() { return TxtNombre;}
    public JTextField getTxtArea() { return TxtArea;}
    public JComboBox getcomboCultivo() { return comboCultivo;}
    public JComboBox getcomboLugar() { return comboLugar;}
    
    // Métodos de utilidad
public void mostrarMensaje(String mensaje) {
    javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}

public void mostrarError(String mensaje) {
    javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

public void limpiarCampos() {
    TxtNombre.setText("");
    TxtArea.setText("");
    comboCultivo.setSelectedIndex(-1);
    comboLugar.setSelectedIndex(-1);
}

    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        // Crear conexión a la base de datos
        CConexion conexion = new CConexion();
        String rol = "productor";
        Connection conexionActiva = CConexion.getConnectionPorRol(rol);

        // ✅ Creamos la vista con conexión
        RegistroLote vista = new RegistroLote(conexionActiva);

        // ✅ Creamos el controlador con la misma conexión
        ControladorRegistroLote controlador = new ControladorRegistroLote(vista, conexionActiva);

        // ✅ Mostramos la ventana
        vista.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtArea;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboCultivo;
    private javax.swing.JComboBox<String> comboLugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}