/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */

import javax.swing.JOptionPane;  
import Modelado.PropietarioDAO;
public class Registroprop extends javax.swing.JFrame {
    
    public Registroprop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Button_siguiente = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Text_Numdocprop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Text_Nomprop = new javax.swing.JTextField();
        Text_Telefonoprop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Text_Correoprop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_contrasena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));
        jPanel1.setForeground(new java.awt.Color(0, 99, 17));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ica_logo_2-removebg-preview (2) (1).png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo.setText("Registro de Propietario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        Button_siguiente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Button_siguiente.setForeground(new java.awt.Color(0, 99, 17));
        Button_siguiente.setText("Siguiente");
        Button_siguiente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 165, 87), 1, true));
        Button_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_siguienteActionPerformed(evt);
            }
        });
        fondo.add(Button_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 130, 30));

        BtnVolver.setBackground(new java.awt.Color(55, 165, 87));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("⮜ REGRESAR");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        fondo.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setText("- Numero de documento (*):");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        Text_Numdocprop.setBackground(new java.awt.Color(225, 237, 227));
        Text_Numdocprop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_Numdocprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NumdocpropActionPerformed(evt);
            }
        });
        fondo.add(Text_Numdocprop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("- Nombre completo (*): ");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, -1));

        Text_Nomprop.setBackground(new java.awt.Color(225, 237, 227));
        Text_Nomprop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_Nomprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NompropActionPerformed(evt);
            }
        });
        fondo.add(Text_Nomprop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 20));

        Text_Telefonoprop.setBackground(new java.awt.Color(225, 237, 227));
        Text_Telefonoprop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_Telefonoprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_TelefonopropActionPerformed(evt);
            }
        });
        fondo.add(Text_Telefonoprop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 310, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("- Numero de telefono (*): ");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 360, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("- Correo electronico (*):");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 360, -1));

        Text_Correoprop.setBackground(new java.awt.Color(225, 237, 227));
        Text_Correoprop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        Text_Correoprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_CorreopropActionPerformed(evt);
            }
        });
        fondo.add(Text_Correoprop, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 310, 20));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("- Contraseña (*): ");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 360, -1));

        TXT_contrasena.setBackground(new java.awt.Color(225, 237, 227));
        TXT_contrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        TXT_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_contrasenaActionPerformed(evt);
            }
        });
        fondo.add(TXT_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 310, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_siguienteActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void Text_NumdocpropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NumdocpropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NumdocpropActionPerformed

    private void Text_NompropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NompropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NompropActionPerformed

    private void Text_TelefonopropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_TelefonopropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_TelefonopropActionPerformed

    private void Text_CorreopropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_CorreopropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_CorreopropActionPerformed

    private void TXT_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_contrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public javax.swing.JButton getButtonSiguiente() {
        return Button_siguiente;
    }

    public javax.swing.JButton getBtnVolver() {
        return BtnVolver;
    }

    public javax.swing.JTextField getTextNumdocprop() {
        return Text_Numdocprop;
    }

    public javax.swing.JTextField getTextNomprop() {
        return Text_Nomprop;
    }

    public javax.swing.JTextField getTextTelefonoprop() {
        return Text_Telefonoprop;
    }

    public javax.swing.JTextField getTextCorreoprop() {
        return Text_Correoprop;
    }

public javax.swing.JTextField getTXTContrasena() {
    return TXT_contrasena;
}

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registroprop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registroprop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registroprop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registroprop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registroprop().setVisible(true);
            }
        });}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton Button_siguiente;
    private javax.swing.JLabel Icon;
    private javax.swing.JTextField TXT_contrasena;
    private javax.swing.JTextField Text_Correoprop;
    private javax.swing.JTextField Text_Nomprop;
    private javax.swing.JTextField Text_Numdocprop;
    private javax.swing.JTextField Text_Telefonoprop;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
