/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
import java.sql.Connection;
import Modelado.CConexion;
import Controlador.ControladorRegistroPredio;
public class RegistroPredio extends javax.swing.JFrame{
    private Connection conexionActiva;
    
    public RegistroPredio() {
        initComponents();
        cmbProductor.removeAllItems();
        cmbProductor.addItem("Seleccione un productor");

        cmbPropietario.removeAllItems();
        cmbPropietario.addItem("Seleccione un propietario"); 
        
        cmbDepartamento.removeAllItems();
        cmbDepartamento.addItem("Seleccione un departamento");
        
        cmbMunicipio.removeAllItems();
        cmbMunicipio.addItem("Seleccione un municipio");
    }
    public RegistroPredio(Connection conexionActiva) {
        this(); // llama al constructor por defecto para inicializar los componentes
        this.conexionActiva = conexionActiva;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVereda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbLugarProdu = new javax.swing.JComboBox<>();
        cmbProductor = new javax.swing.JComboBox<>();
        cmbPropietario = new javax.swing.JComboBox<>();
        cmbDepartamento = new javax.swing.JComboBox<>();
        cmbMunicipio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));
        jPanel1.setForeground(new java.awt.Color(0, 99, 17));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Ica_logo_2-removebg-preview (2) (1).png"))); // NOI18N

        Titulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo.setText("Registro de Predio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        btnRegistrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 99, 17));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(55, 165, 87), 1, true));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        fondo.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, 30));

        BtnVolver.setBackground(new java.awt.Color(55, 165, 87));
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("⮜ REGRESAR");
        BtnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        fondo.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel1.setText("- Nombre (*):");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 210, -1));

        txtNombre.setBackground(new java.awt.Color(225, 237, 227));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        fondo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("- Departamento (*): ");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 360, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("- Municipio (*): ");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 360, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("- Propietario (*):");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 360, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("- Lugar de produccion (*): ");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 360, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setText("- Productor (*): ");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 360, -1));

        txtVereda.setBackground(new java.awt.Color(225, 237, 227));
        txtVereda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 213, 191)));
        txtVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeredaActionPerformed(evt);
            }
        });
        fondo.add(txtVereda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 310, 20));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel9.setText("- Vereda (*):");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 360, -1));

        cmbLugarProdu.setBackground(new java.awt.Color(225, 237, 227));
        cmbLugarProdu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbLugarProdu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbLugarProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 310, -1));

        cmbProductor.setBackground(new java.awt.Color(225, 237, 227));
        cmbProductor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbProductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 310, -1));

        cmbPropietario.setBackground(new java.awt.Color(225, 237, 227));
        cmbPropietario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cmbPropietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 310, -1));

        cmbDepartamento.setBackground(new java.awt.Color(225, 237, 227));
        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 310, -1));

        cmbMunicipio.setBackground(new java.awt.Color(225, 237, 227));
        cmbMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fondo.add(cmbMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeredaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVeredaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(RegistroPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        // ✅ Conexión usando tu clase CConexion
        Connection conexionActiva = Modelado.CConexion.getConnectionPorRol("administrador");

        // Crear vista y controlador con la conexión activa
        RegistroPredio vista = new RegistroPredio();
        ControladorRegistroPredio controlador = new ControladorRegistroPredio(vista, conexionActiva);
        vista.setVisible(true);
    });
}




// --- Getters públicos para acceder desde el controlador ---
public javax.swing.JButton getBtnRegistrar() {
    return btnRegistrar;
}

public javax.swing.JTextField getTxtNombre() {
    return txtNombre;
}

public javax.swing.JComboBox getCmbDepartamento() {
    return cmbDepartamento;
}

public javax.swing.JComboBox getCmbMunicipio() {
    return cmbMunicipio;
}

public javax.swing.JTextField getTxtVereda() {
    return txtVereda;
}


public javax.swing.JComboBox getCmbProductor() {
    return cmbProductor;
}

public javax.swing.JComboBox getCmbPropietario() {
    return cmbPropietario;
    
}


public javax.swing.JButton getBtnVolver(){
    return BtnVolver;
}
public javax.swing.JComboBox getCmbLugarProdu(){
    return cmbLugarProdu;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JComboBox<String> cmbLugarProdu;
    private javax.swing.JComboBox<String> cmbMunicipio;
    private javax.swing.JComboBox<String> cmbProductor;
    private javax.swing.JComboBox<String> cmbPropietario;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVereda;
    // End of variables declaration//GEN-END:variables
}
