package Vista;

import Controlador.ControladorInspeccion;
import Modelado.SolicitudInspeccion;
import java.util.List;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VerInspeccion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerInspeccion.class.getName());

    private Connection conexion;
    private int idTecnico;

    public VerInspeccion(Connection conexion, int idTecnico) {
    initComponents();
    this.conexion = conexion;
    this.idTecnico = idTecnico;
}


    // ========================
    //  SETTERS / GETTERS
    // ========================
    public void setIdTecnico(int id) {
        this.idTecnico = id;
    }

    public int getIdTecnico() {
        return this.idTecnico;
    }

    public DefaultTableModel getModelo() {
        return (DefaultTableModel) tablaSolicitudes.getModel();
    }

    // ========================
    //   CARGAR TABLA
    // ========================
    public void cargarSolicitudes(List<SolicitudInspeccion> lista) {
        DefaultTableModel modelo = getModelo();
        modelo.setRowCount(0);

        for (SolicitudInspeccion s : lista) {
            modelo.addRow(new Object[]{
                s.getIdSolicitud(),
                s.getNumLote(),
                s.getFechaAsignacion(),
                s.getEstado()
            });
        }
    }

    // ========================
    //   CONSTRUCTOR
    // ========================
    public VerInspeccion() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        btnRealizar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 99, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 490));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono100.png"))); // NOI18N
        jLabel3.setToolTipText("");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(212, 240, 221));
        btnRegresar.setForeground(new java.awt.Color(34, 103, 54));
        btnRegresar.setText("⮜ Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 163, 130)));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        fondo.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 100, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Ver Inspecciones Pendientes");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, -1));

        jPanel4.setBackground(new java.awt.Color(55, 165, 87));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 5));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        fondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, -1));

        tablaSolicitudes.setBackground(new java.awt.Color(235, 255, 235));
        tablaSolicitudes.setForeground(new java.awt.Color(0, 99, 17));
        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Solicitud", "Nombre de Lote", "Fecha de Asignación", "Estado"
            }
        ));
        tablaSolicitudes.setGridColor(new java.awt.Color(0, 99, 17));
        tablaSolicitudes.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(tablaSolicitudes);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 720, 250));

        btnRealizar.setBackground(new java.awt.Color(212, 240, 221));
        btnRealizar.setForeground(new java.awt.Color(34, 103, 54));
        btnRealizar.setText("✔️ Realizar");
        btnRealizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 163, 130)));
        btnRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarActionPerformed(evt);
            }
        });
        fondo.add(btnRealizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 100, 30));

        btnActualizar.setBackground(new java.awt.Color(212, 240, 221));
        btnActualizar.setForeground(new java.awt.Color(34, 103, 54));
        btnActualizar.setText("🔄 Actualizar");
        btnActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(125, 163, 130)));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        fondo.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 100, 30));

        jPanel2.setBackground(new java.awt.Color(55, 165, 87));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 480, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JButton getBtnRealizar() {
        return btnRealizar;
    }

    public JTable getTablaSolicitudes() {
        return tablaSolicitudes;
    }
    public static void main(String args[]) {

  
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRealizar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
